# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_joined',
            new_name='date',
        ),
    ]
